# CF Pages/Workers Wrangler config file
name = "ideoxan-www-next"

account_id = "fc7469b1bbe987ee5b82926ae054d5f3"
workers_dev = true

[vars]
WORKER_ENV = "development"
# Secrets:
# - SUPABASE_URL_DEV
# - SUPABASE_SECRET_KEY_DEV
# - SUPABASE_URL
# - SUPABASE_SECRET_KEY
# - SUPABASE_ANON_KEY
# - COOKIE_SECRET
# - TESSERACT_URL
# set them using `wrangler secret put <name>`
# see https://developers.cloudflare.com/workers/cli-wrangler/commands#secret for more info

[env.production]
name = "ideoxan-www"
[env.production.vars]
WORKER_ENV = "production"

